### ISSUE TITLE
Transmitting an RoCrate instance over a network

### ISSUE THREAD

**Issue by StuartWheater** [kit-data-manager/ro-crate-java#122]
I am attempting to send RoCrates over HTTP and AMQP, this appears to require serializing and deserializing RoCrates to JSON / 
Byte array.

I have attempted to use FasterXML Jackson but was unable to use successfully readValue / convertValue to create RoCrate objects (see error below).

Is there another way to serializing and deserializing RoCrates to be transmitted over the network.

Stuart

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `edu.kit.datamanager.ro_crate.entities.data.RootDataEntity` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"rootDataEntity":{"name":"Request","description":"74e0d9a7-f175-450d-8726-73c3d07579c0","@id":"./","@type":"Dataset","hasPart":[{"@id":"http://example.org/8447fd4d-fbb8-45cf-9c55-f590ed775eb0"},{"@id":"http://example.org/35f215f2-2aec-42a7-bea9-c01e31ed3dcb"}]},"jsonDescriptor":{"about":{"@id":"./"},"conformsTo":{"@id":"https://w3id.org/ro/crate/1.1"},"@id":"ro-crate-metadata.json","@type":"CreativeWork"},"untrackedFiles":[],"allDataEntities":[{"Answer to the Ultimate Question of Life, The Univ"[truncated 1097 chars]; line: 1, column: 20] (through reference chain: edu.kit.datamanager.ro_crate.RoCrate["rootDataEntity"])

**Comment by StuartWheater** [comment]
Hi Andreas,
     My ultimate goal is to pass an RoCrate between to independent organization, as a AMQP message. The messages representing an invocation of an analysis service, both requests and responds. I don't think just the metadata will be sufficient, but I will check.

I will look at modifying Writer class to create an in-memory Zip or BagIt.

Stuart

**Comment by Pfeil** [comment]
In this case, the [`ZipWriter`](https://github.com/kit-data-manager/ro-crate-java/blob/main/src/main/java/edu/kit/datamanager/ro_crate/writer/ZipWriter.java) class will help you to understand the process of generating a valid zipped crate. The [zip library we use](https://github.com/srikanth-lingala/zip4j) does not seem to have any in-memory features at first glance, but you are of course not restricted to this library. As a workaround, it may be useful to write it to a temporary directory before reading it again for transmission.

Is your scenario limited to rather small crates? Sending AMQP messages with crates of multiple gigabytes may be not too practical. In such cases, I could imagine to work around this by storing the crate in a repository and distributing a link (and maybe required credentials or so, depending on the scenario) via the message.

Reading this [possibly outdated statement](https://www.cloudamqp.com/blog/what-is-the-message-size-limit-in-rabbitmq.html) and the references given in it, I would not send messages with more than 100mb, although I have no practical experience with large messages, and it may depend on the message broker you use.

**Comment by StuartWheater** [comment]
Thank you. Yes the request and responses are expected to be relatively small, as the analysis is being performed at the data. The AMQP size restrictions shouldn't be an issue.

**Comment by Pfeil** [comment]
You're welcome. I see, so this will be no issue on your side. I'll close the issue for now. If you have any other question, feel free to open another issue or reopen this one. Thanks!
