### ISSUE TITLE
Re-evaluate group and package names.

### ISSUE THREAD

**Issue by Pfeil** [kit-data-manager/ro-crate-java#13]
- In `build.gradle` it says `group 'org.example'`. It should be changed, but I am not sure which parts exactly it will affect.
- Also, the library uses `edu.kit.crate` as the high level package name. Should we reconsider this to be e.g. `edu.kit.ro_crate`? Or even `edu.kit.datamanager.ro_crate`?

**Comment by VolkerHartmann** [comment]
As you already decided for group 'edu.kit.datamanager' I would also move the classes to package edu.kit.datamanager.ro_crate.
But 'edu.kit' is also fine for me. At least the high level package name and the group name should be the same.
By the way: We should get rid of the unused Main class.

**Comment by Pfeil** [comment]
> At least the high level package name and the group name should be the same.

I agree.

> As you already decided for group 'edu.kit.datamanager'

How did I decide that? :D Well, I think it makes sense as it is in the datamanager github organization. I wonder especially if the group is required e.g. by the maven repository or so for upload. Because if so, opening a discussion about a different group name would not make sense.

> By the way: We should get rid of the unused Main class.

Yes, I will do it.

---

Ok let me summarize; we will do:

group name: edu.kit.**datamanager** (before: edu.kit)
module hierarchy: edu.kit.datamanager.**ro_crate**. ... (before: crate)

right?

**Comment by ThomasJejkal** [comment]
Group name should be edu.kit.datamanager I guess. I remember something that for OSSRH I had to prove that I "own" the domain. For edu.kit we can't. :-)

**Comment by Pfeil** [comment]
For the module name, `crate` -> `ro_crate`? Or even `ro-crate-java` to match the libraries name?

**Comment by ThomasJejkal** [comment]
ro-crate4j ?

**Comment by Pfeil** [comment]
According to https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html, this would be `ro_crate4j` then. I am not sure if I like to confuse people by having so different names (ro-crate-java and ro_crate4j), it sounds like two different libraries. `ro_crate` is a bit similar there, which is why I think about using the full name. But as is only emits the obvious part, I think it might not be too bad.
