### ISSUE TITLE
Removing properties from entities is too complicated

### ISSUE THREAD

**Issue by Code42Cate** [kit-data-manager/ro-crate-java#41]
AFAIK, the easiest way to delete a property by name from an entity is this one:
```java
entity.setProperties(entity.getProperties().remove("property_name"));
````
I don't like that we have to work with JsonNodes to delete properties, maybe adding a very simple 
```java
void removeProperty(String key)
```
would be nicer? I think we would only need to add this to the AbstractEntity class.

**Comment by Code42Cate** [comment]
Turns out I was kinda wrong, you can just do:
```java
entity.getProperties().remove(property);
```
I still don't really like it, but not enough to fix it

**Comment by Pfeil** [comment]
For documentation: There is now `removeProperty(...)` and `removeProperties(...)` as a shortcut.
