### ISSUE TITLE
Check the valid use of lists in our data structures

### ISSUE THREAD

**Issue by Pfeil** [kit-data-manager/ro-crate-java#44]
We use lists in many places, and I think in most of them a set would be the better solution. API changes will be possible here, though. So we have to be careful and deprecate old APIs.

**Comment by Code42Cate** [comment]
In `AbstractDataEntityBuilder`, `List<String> authors = new ArrayList<>();` should be a set.

**Comment by Pfeil** [comment]
Also, this builder method takes a list and puts things into a set. From the functionality perspective, allowing all Collections<String> would be possible. This is also something we should check. This one should not even break the API as List also implements Collection. Probably there are more places where we can make use of Collection<>.
https://github.com/kit-data-manager/ro-crate-java/blob/146f40c7c635ff750d5abcd0a9ad31bc25d225f6/src/main/java/edu/kit/datamanager/ro_crate/entities/AbstractEntity.java#L342

**Comment by Pfeil** [comment]
We should consider keeping the order of author lists (and see how we currently do it). While we'll need to support that, I would like to encourage to give roles to people, like author or reviewer, via the API.

**Comment by Pfeil** [comment]
For the APIs, we should consider using Collections and/or Streams. Not yet sure what the best use case would be in our case. Internally we may use what is there for now, or adjust it to our needs.

Related: https://www.baeldung.com/java-return-stream-collection
